Liga.Web.Ux/Controllers/InjuriesController.cs
using Liga.Domain.Entities;
using Liga.Infrastructure.Data;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace Liga.Web.UI.Controllers
{
    [Authorize(Roles = "Administrador, Comisionado")]
    public class InjuriesController : BaseController
    {
        private Liga_DBContext db = new Liga_DBContext();

        //
        // GET: /Injuries/

        public ActionResult Index()
        {
            var injuries = db.Injuries;
            return View(injuries.ToList());
        }

        //
        // GET: /Injuries/Details/5

        public ActionResult Details(int id = 0)
        {
            Injuries injuries = db.Injuries.Find(id);
            if (injuries == null)
            {
                return HttpNotFound();
            }
            return View(injuries);
        }

        //
        // GET: /Injuries/Create

        public ActionResult Create()
        {
            ViewBag.IdPlayer = new SelectList(db.Players.OrderBy(x => x.CompleteName), "Id", "CompleteName");
            ViewBag.IdType = new SelectList(db.InjuryTypes, "Id", "Description");
            return View();
        }

        //
        // POST: /Injuries/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Injuries injuries)
        {
            if (ModelState.IsValid)
            {
                db.Injuries.Add(injuries);
                if (injuries.GamesRest > 0)
                {
                    var pl = db.Players.FirstOrDefault(x => x.Id == injuries.IdPlayer);
                    pl.Injuried = 1;
                    db.Entry(pl).State = EntityState.Modified;
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdPlayer = new SelectList(db.Players.OrderBy(x => x.CompleteName), "Id", "CompleteName", injuries.IdPlayer);
            ViewBag.IdType = new SelectList(db.InjuryTypes, "Id", "Description", injuries.IdType);
            return View(injuries);
        }

        //
        // GET: /Injuries/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Injuries injuries = db.Injuries.Find(id);
            if (injuries == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdPlayer = new SelectList(db.Players.OrderBy(x => x.CompleteName), "Id", "CompleteName", injuries.IdPlayer);
            ViewBag.IdType = new SelectList(db.InjuryTypes, "Id", "Description", injuries.IdType);
            return View(injuries);
        }

        //
        // POST: /Injuries/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Injuries injuries)
        {
            if (ModelState.IsValid)
            {
                db.Entry(injuries).State = EntityState.Modified;
                if(injuries.GamesRest == 0)
                {
                    var pl = db.Players.FirstOrDefault(x => x.Id == injuries.IdPlayer);
                    pl.Injuried = 0;
                    db.Entry(pl).State = EntityState.Modified;
                }
                else
                {
                    var pl = db.Players.FirstOrDefault(x => x.Id == injuries.IdPlayer);
                    pl.Injuried = 1;
                    db.Entry(pl).State = EntityState.Modified;
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdPlayer = new SelectList(db.Players.OrderBy(x=>x.CompleteName), "Id", "CompleteName", injuries.IdPlayer);
            ViewBag.IdType = new SelectList(db.InjuryTypes, "Id", "Description", injuries.IdType);
            return View(injuries);
        }

        //
        // GET: /Injuries/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Injuries injuries = db.Injuries.Find(id);
            if (injuries == null)
            {
                return HttpNotFound();
            }
            return View(injuries);
        }

        //
        // POST: /Injuries/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Injuries injuries = db.Injuries.Find(id);
            db.Injuries.Remove(injuries);
            var pl = db.Players.FirstOrDefault(x => x.Id == injuries.IdPlayer);
            pl.Injuried = 0;
            db.Entry(pl).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult GetIncompleteInjuries()
        {
            List<FlashInjuryReport> listaLesiones = new List<FlashInjuryReport>();
            List<Injuries> InjuryList = db.Injuries.Where(x => x.GamesRest > 0).Take(20).ToList();
            foreach (Injuries injury in InjuryList)
            {
                FlashInjuryReport lesion = new FlashInjuryReport();
                lesion.sLogo = (injury.Player != null && injury.Player.LVNBAFranchis != null ? injury.Player.LVNBAFranchis.Icono : ""); // injury.Player.LVNBAFranchis.Icono; 
                lesion.idPlayer = injury.IdPlayer;
                lesion.sCompleteName = (injury.Player != null ? injury.Player.AbrevName : "");
                lesion.iGamesRest = injury.GamesRest;
                listaLesiones.Add(lesion);
            }
            return Json(listaLesiones.ToList());
        }


        [AllowAnonymous]
        public ActionResult InjuryResume()
        {
            int iSeason = db.Parameters.First().Temporada;
            InjuryResume resumen = new InjuryResume
            {
                ListaLesionados = db.Injuries.Where(x => x.GamesRest > 0),
                ListaPartidosPerdidosPorLesion = db.InjuryGames.Where(x => x.Game.season == iSeason),
                ListaResumenLesiones = db.ResumenLesiones
            };
            return View(resumen);
        }

    }
    public class FlashInjuryReport
    {
        public string sLogo { get; set; }
        public int iGamesRest { get; set; }
        public string sCompleteName { get; set; }
        public int idPlayer { get; set; }

    }

    

    
}

Liga.Web.Ux/Controllers/StatsController.cs
using Liga.Domain.Entities;
using Liga.Infrastructure.Data;
using Liga.Infrastructure.Data.Repository;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web.Mvc;

namespace Liga.Web.UI.Controllers
{
    public class StatsController : BaseController
    {
        private readonly int Season = new Liga_DBContext().Parameters.First().Temporada;
        private Liga_DBContext db = new Liga_DBContext();

        //RankStats in HomePage
        [HttpPost]
        public ActionResult GetTopFivePPGPlayers()
        {
            try
            {
                var res = db.RankPPGs.Take(5).ToList();
                var lista = new List<TopPlayerLists>();
                foreach(var pl in res)
                {
                    var top = new TopPlayerLists
                    {
                        CompleteName = pl.CompleteName,
                        FaceImage = pl.FaceImage,
                        Logo = pl.Logo,
                        STAT = pl.PPG,
                        id = pl.Player,
                        Tipo = "PPG"
                    };
                    lista.Add(top);
                }
                return Json(lista.ToList());
            }
            catch(Exception ex)
            {
                return null;
            }
        }
        [HttpPost]
        public ActionResult GetTopFiveAPGPlayers()
        {
            try
            {
                var res = db.RankAPGs.Take(5).ToList();
                var lista = new List<TopPlayerLists>();
                foreach (var pl in res)
                {
                    var top = new TopPlayerLists
                    {
                        CompleteName = pl.CompleteName,
                        FaceImage = pl.FaceImage,
                        Logo = pl.Logo,
                        STAT = pl.APG,
                        id = pl.Player,
                        Tipo = "APG"
                    };
                    lista.Add(top);
                }
                return Json(lista.ToList());
            }
            catch (Exception ex)
            {
                return null;
            }
        }
        [HttpPost]
        public ActionResult GetTopFiveFGPlayers()
        {
            try
            {
                var res = db.RankFGs.Take(5).ToList();
                var lista = new List<TopPlayerLists>();
                foreach (var pl in res)
                {
                    var top = new TopPlayerLists
                    {
                        CompleteName = pl.CompleteName,
                        FaceImage = pl.FaceImage,
                        Logo = pl.Logo,
                        STAT = pl.FG,
                        id = pl.Player,
                        Tipo = "FG"
                    };
                    lista.Add(top);
                }
                return Json(lista.ToList());
            }
            catch (Exception ex)
            {
                return null;
            }
        }
        [HttpPost]
        public ActionResult GetTopFiveRPGPlayers()
        {
            try
            {
                var res = db.RankRPGs.Take(5).ToList();
                var lista = new List<TopPlayerLists>();
                foreach (var pl in res)
                {
                    var top = new TopPlayerLists
                    {
                        CompleteName = pl.CompleteName,
                        FaceImage = pl.FaceImage,
                        Logo = pl.Logo,
                        STAT = pl.RPG,
                        id = pl.Player,
                        Tipo = "RPG"
                    };
                    lista.Add(top);
                }
                return Json(lista.ToList());
            }
            catch (Exception ex)
            {
                return null;
            }
        }
        [HttpPost]
        public ActionResult GetTopFiveSPGPlayers()
        {
            try
            {
                var res = db.RankSPGs.Take(5).ToList();
                var lista = new List<TopPlayerLists>();
                foreach (var pl in res)
                {
                    var top = new TopPlayerLists
                    {
                        CompleteName = pl.CompleteName,
                        FaceImage = pl.FaceImage,
                        Logo = pl.Logo,
                        STAT = pl.SPG,
                        id = pl.Player,
                        Tipo = "SPG"
                    };
                    lista.Add(top);
                }
                return Json(lista.ToList());
            }
            catch (Exception ex)
            {
                return null;
            }
        }
        [HttpPost]
        public ActionResult GetTopFiveBPGPlayers()
        {
            try
            {
                var res = db.RankBPGs.Take(5).ToList();
                var lista = new List<TopPlayerLists>();
                foreach (var pl in res)
                {
                    var top = new TopPlayerLists
                    {
                        CompleteName = pl.CompleteName,
                        FaceImage = pl.FaceImage,
                        Logo = pl.Logo,
                        STAT = pl.BPG,
                        id = pl.Player,
                        Tipo = "BPG"
                    };
                    lista.Add(top);
                }
                return Json(lista.ToList());
            }
            catch (Exception ex)
            {
                return null;
            }
        }

        public ActionResult StatsPlayer(string orderBy, string currentFilter, string searchString, int? page, string message = "")
        {
            ViewBag.CurrentSort = orderBy;
            ViewBag.Message = message;
            var temporada = db.Parameters.FirstOrDefault().Temporada;

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            IQueryable<PlayerStatisticsBySeason> listaPlayers =
            db.PlayerStatisticsBySeasons.Where(x => x.Season == temporada.ToString()).AsQueryable();

            switch (orderBy)
            {
                case "PPG":
                    listaPlayers = listaPlayers.OrderByDescending(s => s.PPG);
                    break;
                case "RPG":
                    listaPlayers = listaPlayers.OrderByDescending(s => s.RPG);
                    break;
                case "SPG":
                    listaPlayers = listaPlayers.OrderByDescending(s => s.SPG);
                    break;
                case "APG":
                    listaPlayers = listaPlayers.OrderByDescending(s => s.APG);
                    break;
                case "F3G":
                    listaPlayers = listaPlayers.OrderByDescending(s => s.F3G);
                    break;
                case "TOO":
                    listaPlayers = listaPlayers.OrderByDescending(s => s.TOO);
                    break;
                case "MPG":
                    listaPlayers = listaPlayers.OrderByDescending(s => s.MPG);
                    break;
                default:
                    listaPlayers = listaPlayers.OrderByDescending(s => s.PPG);
                    break;
            };
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(listaPlayers.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult StatsRookies(int? idSeason, string orderBy, string currentFilter, string searchString, int? page, string message = "")
        {
            ViewBag.CurrentSort = orderBy;
            ViewBag.NameSortParm = string.IsNullOrEmpty(orderBy) ? "PPG" : "";
            ViewBag.Message = message;
            ViewBag.idSeason = (idSeason == null ? Season : idSeason);
            ViewBag.Seasons = db.Games.Where(x => x.Id > 0).Select(x => x.season).Distinct();
            string temporada = (idSeason == null ? Season.ToString() : idSeason.ToString());

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            //////
            IQueryable<PlayerStatisticsBySeason> listaPlayers =
                //db.PlayerStatisticsBySeasons.Where(x => x.Season == temporada).OrderByDescending(x => x.CompleteName).AsQueryable();
                db.PlayerStatisticsBySeasons.Where(x => x.Season == temporada && x.YearsPro <= 4).OrderByDescending(x => x.CompleteName).AsQueryable();
            //listaPlayers = listaPlayersList.AsQueryable();
            //////
            if (!string.IsNullOrEmpty(searchString))
            {
                listaPlayers = listaPlayers.Where(s => s.CompleteName.ToUpper().Contains(searchString.ToUpper()));
            }
            switch (orderBy)
            {
                case "PPG":
                    listaPlayers = listaPlayers.OrderByDescending(s => s.PPG);
                    break;
                case "RPG":
                    listaPlayers = listaPlayers.OrderByDescending(s => s.RPG);
                    break;
                case "SPG":
                    listaPlayers = listaPlayers.OrderByDescending(s => s.SPG);
                    break;
                case "APG":
                    listaPlayers = listaPlayers.OrderByDescending(s => s.APG);
                    break;
                case "F3G":
                    listaPlayers = listaPlayers.OrderByDescending(s => s.F3G);
                    break;
                case "TOO":
                    listaPlayers = listaPlayers.OrderByDescending(s => s.TOO);
                    break;
                case "MPG":
                    listaPlayers = listaPlayers.OrderByDescending(s => s.MPG);
                    break;
                default:

Liga.Web.Ux/Controllers/TestController.cs
using Liga.Service.Impl;
using System.Web.Http;
using System.Web.Mvc;
using AllowAnonymousAttribute = System.Web.Http.AllowAnonymousAttribute;
using HttpGetAttribute = System.Web.Http.HttpGetAttribute;

namespace LVNBA_1.Controllers
{
    [System.Web.Http.Route("api/test")]
    public class TestController : ApiController
    {
        readonly SeasonService serv = new SeasonService();

        [AllowAnonymous]
        [HttpGet]
        public IHttpActionResult TestAsync()
        {
            //int year = 2019;
            //serv.CreateNewSeasonAsync(year);
            return Ok();
        }
    }
}

Liga.Web.Ux/Views/Home/Index.cshtml
@{

    ViewBag.Title = "Indice";
    Layout = "~/Views/Shared/_HomeWebLayout.cshtml";
}
<style>
    .ui-dialog {
        z-index: 5000 !important;
    }
</style>
<section class="featured">
    <div class="row">
        <div class="col-md-12">
            @{
                Html.RenderPartial("PlayerOfensiveStatsView");
            }
        </div>
        <div class="col-md-12">
            @{
                Html.RenderPartial("PlayerDefensiveStatsView");
            }
        </div>
    </div>
</section>
<div class="modal fade" id="dialog-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content" style="width:90%">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="FillTable"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>

@section Scripts{

    <script type="text/javascript">
        $(document).ready(function () {
            $.blockUI();

            $(function () {
                getResults();
                getInjuries();
                getTopPlayers("GetTopFivePPGPlayers", "#playerOFENSEPPG");
                getTopPlayers("GetTopFiveAPGPlayers", "#playerOFENSEAPG");
                getTopPlayers("GetTopFiveFGPlayers", "#playerOFENSEFG");
                getTopPlayers("GetTopFiveRPGPlayers", "#playerDEFENSERPG");
                getTopPlayers("GetTopFiveBPGPlayers", "#playerDEFENSEBPG");
                getTopPlayers("GetTopFiveSPGPlayers", "#playerDEFENSESPG");
                $.unblockUI();
            });
        })


        function runEffect() {
            // most effect types need no options passed by default
            var options = {};
            // run the effect
            $("#InfoHelp").show("Pulsate", options, 500);
        };
    $.fn.parpadeando = function () {

        this.each(function parpadeando() {
            $(this).fadeIn(500).delay(250).css("background-color", "slategrey").fadeOut(500, parpadeando);
        });
    }
    function parpadear() {
        elemento = '#chi';
        $(elemento).fadeIn(500).delay(250).fadeOut(500, parpadear)
    }


function getTopPlayers(actionResult, divToPaint) {
    $.ajax({
        url: "/Stats/" + actionResult,
        data: {},
        dataType: "html",
        type: "POST",
        error: function () {
            //alert("An error occurred.");
        },
        success: function (data) {
            data = eval(data);
            if (data.length > 0) {
                var options = '';
                var i = 0;

                for (temp in data) {
                    var item = data[temp];
                    var imageLogo = '<img   width="15px" height="15px" src="@Url.Content("~/Images/Common/teams/Iconos/#laIMG")"  />';
                    imageLogo = imageLogo.replace("#laIMG", item.Logo);
                    if (i == 0) {
                        options += '<tr class="oddrow player-46-3202">'
                        options += '<td rowspan="5" width="40%" style="background: none; border: 0;">'
                        options += '<img  width="100%" onclick="viewPlayerInfo(' + item.id + ');" style="cursor:pointer" class="topPlayer" src="' + item.FaceImage + '" /></td>'

                        }
                    options += '<td onclick="viewPlayerInfo(' + item.id + ');" style="cursor:pointer" id=' + item.id + ' align="left"> '
                    options += imageLogo + ' ' + item.CompleteName + '</td>'
                    options += '   <td align="right">' + item.STAT.toFixed(1) + '</td></tr>'

                        i = i + 1;
                    }
                    jQuery(divToPaint).html(options);
                }
        }
    });
    }

    function getResults() {
        $.ajax({
            url: "@Url.Action("GetLast10Results", "Results")",
            data: {},
            dataType: "html",
            type: "POST",
            error: function () {
            },
            success: function (data) {
                data = eval(data);
                var options = '';
                options += '<div class="col-12 resultadis"><ul style="background-color:transparent;font-family: arial;"><img src="../Images/resultados.jpg" width="100%"><li style="background-color:transparent">';
                if (data.length > 0) {
                    var i = 0;
                    for (temp in data) {
                        var item = data[temp];
                        i = i + 1;
                        var imageLocal = '<img   width="15px" height="15px" src="@Url.Content("~/Images/Common/teams/Iconos/#laIMG")"  />';
                            imageLocal = imageLocal.replace("#laIMG", item.sLogoLocal);
                            var imageAway = '<img   width="15px" height="15px" src="@Url.Content("~/Images/Common/teams/Iconos/#laIMG")"  />';
                        imageAway = imageAway.replace("#laIMG", item.sLogoAway);

                        options += '<table  style="border-collapse:inherits;border-left-width:0px;color:black;font-weight:bold;width:100%;font-size:10px"><tr style="border-left-width:0px;background-color:transparent;">' +
                             '<td style="width:30%;text-align:right;"><a href="/Rosters/TeamRosters?idTab=3&idTeam=' + item.idTeamAway + '"  title="Resultados '
                            + item.sAbrevAway + '" style="color:black">' + item.sAbrevAway + '&nbsp;&nbsp;' + imageAway+ '</a></td>'

                            + '<td style="width:10%;background-color:transparent;text-align:center"> - </td>'

                            + '<td style="width:30%;"><a href="/Rosters/TeamRosters?idTab=3&idTeam='
                            + item.idTeamLocal + '"   title="Resultados ' + item.sAbrevLocal + '" style="color:black">' + imageLocal + '&nbsp;&nbsp;' + item.sAbrevLocal
                                + '</a></td>' + '<td style="text-align:right;width:30%;"><a class="boxscore" href="/Results/GetScoreInfo?idGame=' + item.idGame + '" id="' + item.idGame + '"  title="BoxScore" style="color:black">'
                            + item.iScoreAway + '-' + item.iScoreLocal + '</a></td>'
                                +'</tr></table>';
                        }
                }
                options += '</li><li style=" padding:10px;"><a style="color:black;" href="/Results/Index" title="Ver Otros Resultados">&laquo; Ver Otros Resultados</a></li></ul></div>';
                jQuery('#firstRightListUL').html(options);

            }
        });
    }
    function getInjuries() {
        $.ajax({
            url: "@Url.Action("GetIncompleteInjuries", "Injuries")",
                data: {},
                dataType: "html",
                type: "POST",
                error: function () {
                //  alert("An error occurred con las lesiones.");
                },
                success: function (data) {
                    data = eval(data);
                    if (data.length > 0) {
                        var options = '';
                        var i = 0;
                        options += '<div class="col-12 resultadis"><ul style="background-color:transparent;font-family: arial;"><img src="../Images/lesiones.jpg" width="100%"><li style="background-color:transparent">';
                        for (temp in data) {
                            var item = data[temp];
                            i = i + 1;
                            var imageLogo = '<img   width="15px" height="15px" src="@Url.Content("~/Images/Common/teams/Iconos/#laIMG")"  />';
                            imageLogo = imageLogo.replace("#laIMG", item.sLogo);
                            options += '<table  style="border-collapse:inherits;border-left-width:0px;background-color:black;color:white;width:100%;font-size:10px"><tr border=""  style="border-left-width:0px;background-color:transparent;"><td style="width:70%;background-color:black;">' + imageLogo + '&nbsp;&nbsp;' + item.sCompleteName + '</td><td style="width:30%;align:center;background-color:black;"><img width="15px" height="15px" src="@Url.Content("~/Images/Common/lesion.png")"  />' + '&nbsp;&nbsp;' + item.iGamesRest + '</td></tr></table>';
                    }
                    options += '</li><li style="background-color:transparent; text-aling:center"><a style="color:white" href="/Injuries/InjuryResume" title="Ver todos los lesionados">&laquo; Ver Lesionados</a></li></ul></div>';
                    jQuery('#InjuryListUL').html(options);
                }
            }
       });
    }

    </script>
}

Liga.Web.Ux/Views/Home/PlayerDefensiveStatsView.cshtml
<div id="my-players-table" class="row">
    <div class="col-12">
        <img src="~/Images/def.jpg" width="100%">
        <table class="table table-striped">                    
            <thead class="thead-dark">
                <tr>
                    <th colspan="2"><a style="font-weight:bold ;color:white"  href="@Url.Action("StatsPlayer", "Stats", new { orden = "RPG" })" title="Ver clasificación detallada">REBOTES</a></th>
                    <th align="right">REB</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <td align="center" colspan="4" id="prev"><a style="font-weight:bold ;color:white" href="/Stats/StatsPlayer/?orden=RPG" title="Ver clasificación detallada">&laquo; Detalle</a></td>
                </tr>
            </tfoot>
            <tbody id="playerDEFENSERPG"></tbody>
        </table>

        <table class="table table-striped">
            <thead class="thead-dark">
                <tr>
                    <th colspan="2"><a style="font-weight:bold ;color:white"  href="/Stats/StatsPlayer/?orden=BPG" title="Ver clasificación detallada">TAPONES</a></th>
                    <th align="right">TAP</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <td align="center" colspan="4" id="prev"><a style="color:white" href="@Url.Action("StatsPlayer", "Stats", new { orden = "BPG" })" title="Ver clasificación detallada">&laquo; Detalle</a></td>
                </tr>
            </tfoot>
            <tbody id="playerDEFENSEBPG"></tbody>
        </table>
        <table  class="table table-striped">
            <thead class="thead-dark">
                <tr>
                    <th colspan="2"><a style="color:white" href="@Url.Action("StatsPlayer", "Stats", new { orden = "SPG" })" title="Ver clasificación detallada">ROBOS</a></th>
                    <th align="right">ROB</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <td align="center" colspan="4" id="prev"><a style="color:white" href="@Url.Action("StatsPlayer", "Stats", new { orden = "SPG" })" title="Ver clasificación detallada">&laquo; Detalle</a></td>
                </tr>
            </tfoot>
            <tbody id="playerDEFENSESPG"></tbody>
        </table>
    </div>
</div>


       

Liga.Web.Ux/Views/Home/PlayerOfensiveStatsView.cshtml
<div id="my-players-table" class="row">
    <div class="col-12">
        <img src="~/Images/ofen.jpg" width="100%">
            <table class="table table-striped">
            <thead class="thead-dark">
                <tr>
                    <th colspan="2"><a style="color:white" href="@Url.Action("StatsPlayer", "Stats", new { orden = "PPG" })" title="Ver clasificación detallada">PUNTOS</a></th>
                    <th align="right">PTS</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <td align="center" colspan="4" id="prev"><a style="font-weight:bold ;color:white" href="@Url.Action("StatsPlayer", "Stats", new { orden = "PPG" })" title="Ver clasificación detallada">&laquo; Detalle</a></td>
                </tr>
            </tfoot>
            <tbody id="playerOFENSEPPG"></tbody>
        </table>

        <table class="table table-striped">
            <thead class="thead-dark">
                <tr>
                    <th colspan="2"><a style="color:white" href="@Url.Action("StatsPlayer", "Stats", new { orden = "ASS" })" title="Ver clasificación detallada">ASISTENCIAS</a></th>
                    <th align="right">ASI</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <td align="center" colspan="4" id="prev"><a style="color:white" href="@Url.Action("StatsPlayer", "Stats", new { orden = "ASS" })" title="Ver clasificación detallada">&laquo; Detalle</a></td>
                </tr>
            </tfoot>
            <tbody id="playerOFENSEAPG"></tbody>
        </table>

        <table class="table table-striped">
            <thead class="thead-dark">
                <tr>
                    <th colspan="2"><a style="color:white" href="@Url.Action("StatsPlayer", "Stats", new { orden = "FG" })" title="Ver clasificación detallada">% TIROS</a></th>
                    <th align="right">FGP</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <td align="center" colspan="4" id="prev"><a style="color:white" href="@Url.Action("StatsPlayer", "Stats", new { orden = "FG" })" title="Ver clasificación detallada">&laquo; Detalle</a></td>
                </tr>
            </tfoot>
            <tbody id="playerOFENSEFG"></tbody>
        </table>

    </div>
</div>

Liga.Web.Ux/Views/Home/Test.cshtml
@model IEnumerable<Liga.Domain.Entities.Players>

@{
    ViewBag.Title = "Test";
}

<h2>Test</h2>

@Html.ActionLink("Vamos","Test",new { idTeam = 13});

@foreach (var item in Model)
{
   <div>@item.CompleteName </div>
}


<div>@Model.Count()</div>