Liga.Web.Ux/Controllers/TradesController.cs
using Liga.Domain.Entities;
using Liga.Infrastructure.Data;
using Liga.Infrastructure.Data.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.Security;

namespace Liga.Web.UI.Controllers
{
    public class TradesController : BaseController
    {
        //
        // GET: /Trades/
        private Liga_DBContext db = new Liga_DBContext();
        

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult TransfersInfo()
        {
            List<LVNBAFranchises> LVNBAFranchisesList = db.LVNBAFranchises.ToList();
            return View(LVNBAFranchisesList);
        }

        public JsonResult GetTransferibles(int idFranchise)
        {
            var transferibles = db.Players.Where(x => x.IdState == 1 && x.ActualTeam == idFranchise).Select(x => new
            {
                Jugador = x.CompleteName,
                JugadorImagen = x.FaceImage,
                Equipo = x.LVNBAFranchis.Name,
                EquipoImagen = x.LVNBAFranchis.Icono.Replace(".png", ".jpg")
            });
            return Json(transferibles, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetTransferiblesOld(int idFranchise)
        {
            var franchises = db.TransfersPlayersLists.Where(x => x.IdFranchise == idFranchise).Select(a => new
            {
                Jugador = a.Player.CompleteName
            });
            return Json(franchises, JsonRequestBehavior.AllowGet);
        }

        public ActionResult TransfersInfoOld()
        {            
            TradatorModel tModel = new TradatorModel();
            Salarios sal = new Salarios();
            if (ViewBag.IsManagerWithTeam == true)
            {
                int? idTeam = GetManagerTeam();
               

                ViewBag.IdTeam1 = new SelectList(db.LVNBAFranchises.OrderBy(x => x.Name), "Id", "Name", idTeam);
                tModel.ListPlayersTeam1 = new ListPlayersTradeTeam();


                tModel.ListPlayersTeam1.ListPlayersTeam = sal.getSalaryPlayers(idTeam);
                //db.PlayersSalariesFull.Where(x => x.IdLVNBAFranchises == idTeam && x.Player.IdState != 4);
                //foreach (PlayersSalaries salario in tModel.ListPlayersTeam1.ListPlayersTeam)
                //{
                //    if(salario.RookieRights == 1)
                //        salario.Salary1 = 0;
                //}
                tModel.ListPlayersTeam1.ListRoundsTeam = GetRounds(Convert.ToInt32(idTeam));
                tModel.Team1 = db.LVNBAFranchises.Where(x => x.Id == idTeam).First();
               
                tModel.ListPlayersTeam1.PresupuestoActual = sal.getSalaryTeam(Convert.ToInt32(idTeam));
            }
            else
            {
                ViewBag.IdTeam1 = new SelectList(db.LVNBAFranchises.OrderBy(x => x.Name), "Id", "Name", "");
                tModel.ListPlayersTeam1 = new ListPlayersTradeTeam();
            }
            ViewBag.IdTeam2 = new SelectList(db.LVNBAFranchises.OrderBy(x => x.Name), "Id", "Name", "");
            ViewBag.IdTeam3 = new SelectList(db.LVNBAFranchises.OrderBy(x => x.Name), "Id", "Name", "");
            ViewBag.IdTeam4 = new SelectList(db.LVNBAFranchises.OrderBy(x => x.Name), "Id", "Name", "");
            tModel.ListPlayersTeam2 = new ListPlayersTradeTeam();
            tModel.ListPlayersTeam3 = new ListPlayersTradeTeam();
            tModel.ListPlayersTeam4 = new ListPlayersTradeTeam();


            tModel.ListPlayersTeam1.idPosTeam = 1;
            tModel.ListPlayersTeam2.idPosTeam = 2;
            tModel.ListPlayersTeam3.idPosTeam = 3;
            tModel.ListPlayersTeam4.idPosTeam = 4;
            return View(tModel);
        }

        public IEnumerable<Rounds> GetRounds(int idOwner)
        {
            int iSeason = db.Parameters.First().Temporada;
            return db.Rounds.Where(x => x.Owner == idOwner && x.Year == iSeason).AsEnumerable();

        }
        public ActionResult PartialTradeTeam1(int id)
        {
            Salarios sal = new Salarios();
            // TODO: Populate the model (viewmodel) here using the id
            TradatorModel tModel = new TradatorModel();
            tModel.ListPlayersTeam1 = new ListPlayersTradeTeam();
            tModel.ListPlayersTeam1.ListPlayersTeam = sal.getSalaryPlayers(id); // db.PlayersSalariesFull.Where(x => x.IdLVNBAFranchises == id && x.Player.IdState != 4);
            tModel.ListPlayersTeam1.ListRoundsTeam = GetRounds(id);
            tModel.ListPlayersTeam1.idPosTeam = 1;
            //tModel.ListPlayersTeam2.idPosTeam = 2;
            //tModel.ListPlayersTeam3.idPosTeam = 3;
            //tModel.ListPlayersTeam4.idPosTeam = 4;
            return PartialView("TransferTeam", tModel.ListPlayersTeam1);
        }
        public ActionResult PartialRoundTradeTeam1(int id)
        {
            // TODO: Populate the model (viewmodel) here using the id
            TradatorModel tModel = new TradatorModel();
            tModel.ListPlayersTeam1 = new ListPlayersTradeTeam();
            tModel.ListPlayersTeam1.ListPlayersTeam = db.PlayersSalariesFull.Where(x => x.IdLVNBAFranchises == id && x.Player.IdState != 4);
            tModel.ListPlayersTeam1.ListRoundsTeam = GetRounds(id);
            tModel.ListPlayersTeam1.idPosTeam = 1;
            return PartialView("TransferRound", tModel.ListPlayersTeam1);
        }
        public ActionResult PartialTradeTeam2(int id)
        {
            Salarios sal = new Salarios();
            // TODO: Populate the model (viewmodel) here using the id
            TradatorModel tModel = new TradatorModel();
            tModel.ListPlayersTeam2 = new ListPlayersTradeTeam();
            tModel.ListPlayersTeam2.ListPlayersTeam = sal.getSalaryPlayers(id); // db.PlayersSalariesFull.Where(x => x.IdLVNBAFranchises == id && x.Player.IdState != 4);
            tModel.ListPlayersTeam2.ListRoundsTeam = GetRounds(id);
            tModel.ListPlayersTeam2.idPosTeam = 2;
            return PartialView("TransferTeam", tModel.ListPlayersTeam2);
        }
        public ActionResult PartialRoundTradeTeam2(int id)
        {
            // TODO: Populate the model (viewmodel) here using the id
            TradatorModel tModel = new TradatorModel();
            tModel.ListPlayersTeam2 = new ListPlayersTradeTeam();
            tModel.ListPlayersTeam2.ListPlayersTeam = db.PlayersSalariesFull.Where(x => x.IdLVNBAFranchises == id && x.Player.IdState != 4);
            tModel.ListPlayersTeam2.ListRoundsTeam = GetRounds(id);
            tModel.ListPlayersTeam2.idPosTeam =2;
            return PartialView("TransferRound", tModel.ListPlayersTeam2);
        }
        public ActionResult PartialTradeTeam3(int id)
        {
            Salarios sal = new Salarios();
            // TODO: Populate the model (viewmodel) here using the id
            TradatorModel tModel = new TradatorModel();
            tModel.ListPlayersTeam3 = new ListPlayersTradeTeam();
            tModel.ListPlayersTeam3.ListPlayersTeam = sal.getSalaryPlayers(id); // db.PlayersSalariesFull.Where(x => x.IdLVNBAFranchises == id && x.Player.IdState != 4);
            tModel.ListPlayersTeam3.ListRoundsTeam = GetRounds(id);
            tModel.ListPlayersTeam3.idPosTeam = 3;
            return PartialView("TransferTeam", tModel.ListPlayersTeam3);
        }
        public ActionResult PartialRoundTradeTeam3(int id)
        {
            // TODO: Populate the model (viewmodel) here using the id
            TradatorModel tModel = new TradatorModel();
            tModel.ListPlayersTeam3 = new ListPlayersTradeTeam();
            tModel.ListPlayersTeam3.ListPlayersTeam = db.PlayersSalariesFull.Where(x => x.IdLVNBAFranchises == id && x.Player.IdState != 4);
            tModel.ListPlayersTeam3.ListRoundsTeam = GetRounds(id);
            tModel.ListPlayersTeam3.idPosTeam = 3;

            return PartialView("TransferRound", tModel.ListPlayersTeam3);
        }
        public ActionResult PartialTradeTeam4(int id)
        {
            Salarios sal = new Salarios();
            // TODO: Populate the model (viewmodel) here using the id
            TradatorModel tModel = new TradatorModel();
            tModel.ListPlayersTeam4 = new ListPlayersTradeTeam();
            tModel.ListPlayersTeam4.ListPlayersTeam = sal.getSalaryPlayers(id); // db.PlayersSalariesFull.Where(x => x.IdLVNBAFranchises == id && x.Player.IdState != 4);
            tModel.ListPlayersTeam4.ListRoundsTeam = GetRounds(id);
            tModel.ListPlayersTeam4.idPosTeam = 4;
            return PartialView("TransferTeam", tModel.ListPlayersTeam4);
        }
        public ActionResult PartialRoundTradeTeam4(int id)
        {
            // TODO: Populate the model (viewmodel) here using the id
            TradatorModel tModel = new TradatorModel();
            tModel.ListPlayersTeam4 = new ListPlayersTradeTeam();
            tModel.ListPlayersTeam4.ListPlayersTeam = db.PlayersSalariesFull.Where(x => x.IdLVNBAFranchises == id && x.Player.IdState != 4);
            tModel.ListPlayersTeam4.ListRoundsTeam = GetRounds(id);
            tModel.ListPlayersTeam4.idPosTeam = 4;
            return PartialView("TransferRound", tModel.ListPlayersTeam4);
        }


        public ActionResult PartialSalaryTradeTeam1(int id)
        {
            Salarios sal = new Salarios();
            // TODO: Populate the model (viewmodel) here using the id
            TradatorModel tModel = new TradatorModel();
            tModel.ListPlayersTeam1 = new ListPlayersTradeTeam();
            tModel.ListPlayersTeam1.ListPlayersTeam = sal.getSalaryPlayers(id); // db.PlayersSalariesFull.Where(x => x.IdLVNBAFranchises == id && x.Player.IdState != 4);
            tModel.ListPlayersTeam1.ListRoundsTeam = GetRounds(id);
            tModel.ListPlayersTeam1.idPosTeam = 1;
            tModel.ListPlayersTeam1.PresupuestoActual = sal.getSalaryTeam(Convert.ToInt32(id));

Liga.Web.Ux/Views/Trades/Maschulo TransfersInfo.cshtml
@model Liga.Domain.Entities.TradatorModel 

@{
    ViewBag.Title = "TransfersInfo";
    Layout = "~/Views/Shared/_WebWithoutColumnsLayout.cshtml";
}
<style>
    .tradeLogoTeam {
        opacity: 1;
        width: 80px;
        /*background-image:url('../../Images/Common/teams/Iconos/MIN.png');*/
    }
    body {
  
  
    
}
         
    
</style>
<script>
    $(function () {
    $(".draggable").tooltip({
            track: true
        });
    $(".draggable").draggable({ revert: "invalid" });
    $( "#droppable" ).droppable({
      drop: function( event, ui ) {
        $( this )
          .addClass( "ui-state-highlight" )
          .find( "p" )
            .html( "Dropped!" );
      }
    });
  });
  </script>
<table style="font-size: 10px;width:100%;height:100%;background-color:whitesmoke;">
    <tr>
        <td><table>

         @foreach (var player in Model.ListPlayersTeam1)
         {
             <tr>
             <td class="draggable" id="@player.Id" class="ui-widget-content">@player.Player.AbrevName</td>
             <td>@player.Salary1</td><td><a href="#" title="@player.Salary2 || @player.Salary3 || @player.Salary4 || @player.Salary5 || @player.Salary6  ">Ver Salario</a></td>
             </tr>
         }</table>  

        </td><td>2</td><td>3</td><td style="font-size: 1px; text-align:center;">        <img class="tradeLogoTeam" src="~/Images/Common/teams/Iconos/@Model.Team1.Icono" /><br />
      @Html.DropDownList("IdTeam1", String.Empty)

        </td><td>5</td><td>6</td><td>7</td>
        <td><table>
<tr>
         @foreach (var player in Model.ListPlayersTeam1)
         {
             
             <td class="draggable" id="@player.Id" class="ui-widget-content" style="float:right"> @{Html.RenderPartial("TradePlayerCard", player.Player);}</td>
            
         }</tr></table>  
        </td>
    </tr>
    <tr>
        <td><img class="tradeLogoTeam" src="~/Images/Common/teams/Iconos/@Model.Team2.Icono" /><br />
                    @Html.DropDownList("IdTeam2", String.Empty)

        </td><td>2</td><td>3</td><td>4</td>
        <td>5</td><td>6</td><td>7</td><td style="text-align:right"><img style="" class="tradeLogoTeam" src="~/Images/Common/teams/Iconos/@Model.Team3.Icono" /> <br />
                               @Html.DropDownList("IdTeam3", String.Empty)
</td>

    </tr>
    <tr><td><table>

         @foreach (var player in Model.ListPlayersTeam1)
         {
             <tr>
             <td class="draggable" id="@player.Id" class="ui-widget-content">@player.Player.AbrevName</td>
             <td>@player.Salary1</td><td>@player.Salary2</td><td>@player.Salary3</td><td>@player.Salary4</td><td>@player.Salary5</td><td>@player.Salary6</td>
             </tr>
         }</table> 

        </td><td>2</td><td>3</td><td style="text-align:center"><img class="tradeLogoTeam"  src="~/Images/Common/teams/Iconos/@Model.Team4.Icono" /> <br />
                           @Html.DropDownList("IdTeam4", String.Empty)
</td><td>5</td><td>6</td><td>7</td><td>
    <table>

         @foreach (var player in Model.ListPlayersTeam1)
         {
             <tr>
             <td class="draggable" id="@player.Id" class="ui-widget-content">@player.Player.AbrevName</td>
             <td>@player.Salary1</td><td>@player.Salary2</td><td>@player.Salary3</td><td>@player.Salary4</td><td>@player.Salary5</td><td>@player.Salary6</td>
             </tr>
         }</table> 
                                   </td></tr>
</table>

Liga.Web.Ux/Views/Trades/TransferRound.cshtml
@model Liga.Domain.Entities.ListPlayersTradeTeam
  
 
<ul id="galleryRound_@Model.idPosTeam" class="gallery ui-helper-reset ui-helper-clearfix">
         @foreach (var ronda in Model.ListRoundsTeam)
         {
             <li id="@ronda.Id"  idGallery="galleryRound_@Model.idPosTeam">
                <div>@ronda.Type ª</div>
                <div>@ronda.LVNBAFranchis.NickName </div>
                <div>@ronda.Year</div>
             </li>
         }
</ul> 

Liga.Web.Ux/Views/Trades/TransferSalary.cshtml
@model Liga.Domain.Entities.ListPlayersTradeTeam
@*   <script>
       $(function () {
           $('.presupuestoSpan').autoNumeric('init', { aSep: '.', aDec: ',', aSign: '$ ', mDec: '0' });
           $('.presupuestoSpan').attr("disabled", true);

       });
    </script>*@
@*@Html.TextBox("presupuesto", Model.PresupuestoActual, new { id = "Presupuesto" + Model.idPosTeam, @class = "presupuestoSpan", style = " float:left;width:120px; font-size:16px;background-color:black;color:white", maxlength = "14" })*@
 
@Model.PresupuestoActual

Liga.Web.Ux/Views/Trades/TransferTeam.cshtml
@model Liga.Domain.Entities.ListPlayersTradeTeam
<script src="~/Scripts/quickfit/jquery.textfill.min.js"></script>
   <script>

       $(function () {
           $('.salarioGallery').autoNumeric('init', { aSep: '.', aDec: ',', aSign: '$ ', mDec: '0' });
           $('.playerName').textfill({ maxFontPixels: 10 });
           var $galleryTeam1 = $("#galleryTeam_1"), $galleryTeam2 = $("#galleryTeam_2"), $galleryTeam3 = $("#galleryTeam_3"), $galleryTeam4 = $("#galleryTeam_4"),
         $trashTeam1 = $("#trashTeam1"), $trashTeam2 = $("#trashTeam2"), $trashTeam3 = $("#trashTeam3"), $trashTeam4 = $("#trashTeam4");
           $galleryRound1 = $("#galleryRound_1"), $galleryRound2 = $("#galleryRound_2"), $galleryRound3 = $("#galleryRound_3"), $galleryRound4 = $("#galleryRound_4");
           var $comboTeam1 = $("#IdTeam1");

           $("li", ".gallery").draggable({
               cancel: "a.ui-icon", // clicking an icon won't initiate dragging
               revert: "invalid", // when not dropped, the item will revert back to its initial position
               containment: "document",
               helper: "clone",
               cursor: "default"
           });

           // resolve the icons behavior with event delegation
           $("ul.gallery > li").click(function (event) {
               var $item = $(this),
                 $target = $(event.target);
               if ($target.is("a.ui-icon-trash")) {
                   deleteImage($item);
               } else if ($target.is("a.ui-icon-refresh")) {
                     
                   eliminaSuSalario_aux($item);
                   event.stopImmediatePropagation()
                   recycleImage($item, $("#" + $(this).attr('idGallery').toString()));
                   

               }

               return false;
           });

           function eliminaSuSalario_aux(jugador) {
               
               var salarioJugador = dameSalario(jugador);
               var equipo = $(jugador).attr('idGallery').toString(); // de que equipo pertenece
               switch (equipo) {
                   case "galleryTeam_1":
                       salarioEntranteEquipoActual = $('#divSalaryExit1').autoNumeric('get');
                       $('#divSalaryExit1').autoNumeric('set', parseFloat(salarioEntranteEquipoActual) - parseFloat(salarioJugador));
                       break;
                   case "galleryTeam_2":
                       salarioEntranteEquipoActual = $('#divSalaryExit2').autoNumeric('get');
                       $('#divSalaryExit2').autoNumeric('set', parseFloat(salarioEntranteEquipoActual) - parseFloat(salarioJugador));
                       break;
                   case "galleryTeam_3":
                       salarioEntranteEquipoActual = $('#divSalaryExit3').autoNumeric('get');
                       $('#divSalaryExit3').autoNumeric('set', parseFloat(salarioEntranteEquipoActual) - parseFloat(salarioJugador));
                       break;
                   case "galleryTeam_4":
                       salarioEntranteEquipoActual = $('#divSalaryExit4').autoNumeric('get');
                       $('#divSalaryExit4').autoNumeric('set', parseFloat(salarioEntranteEquipoActual) - parseFloat(salarioJugador));
                       break;
               }

               //como saber en que trash esta? para decrecer el saliente
               var papeleraSt = $(jugador).parents().eq(1).attr('idTrash').toString();
               var papelera = $(jugador).parents().eq(1).attr('idTrash');

               salarioSalienteEquipoActual = $('#divSalaryEntry' + papelera).autoNumeric('get');
               $('#divSalaryEntry' + papelera).autoNumeric('set', parseFloat(salarioSalienteEquipoActual) - parseFloat(salarioJugador));

               calculaDffSal();
               calculaPresCalc();
           }
           function calculaDffSal() {

               for (i = 1; i < 5; i++) {
                   $('#divSalaryDiff' + i).autoNumeric('set', parseFloat($('#divSalaryEntry' + i).autoNumeric('get')) - parseFloat($('#divSalaryExit' + i).autoNumeric('get')));

               }

           }
           function calculaPresCalc() {

               for (i = 1; i < 5; i++) {
                   $('#divSalaryCalc' + i).autoNumeric('set', parseFloat($('#divPresupuesto' + i).autoNumeric('get')) + parseFloat($('#divSalaryDiff' + i).autoNumeric('get')));

               }
           }
           function dameSalario(objeto) {
               var salarioJugador = 0;
               var team = $(objeto).attr('idGallery').toString();
               switch (team) {
                   case "galleryTeam_1":
                       if ($(objeto).attr('salary') != undefined) {
                           salarioJugador = $(objeto).attr('salary').toString();
                       }
                       break;
                   case "galleryTeam_2":
                       if ($(objeto).attr('salary') != undefined) {
                           salarioJugador = $(objeto).attr('salary').toString();
                       }
                       break;
                   case "galleryTeam_3":
                       if ($(objeto).attr('salary') != undefined) {
                           salarioJugador = $(objeto).attr('salary').toString();
                       }
                       break;
                   case "galleryTeam_4":
                       if ($(objeto).attr('salary') != undefined) {
                           salarioJugador = $(objeto).attr('salary').toString();
                       }
                       break;
               }
               return salarioJugador;
           }
           // image deletion function
           var recycle_icon = "<a href='link/to/recycle/script/when/we/have/js/off' title='Recycle this image' class='ui-icon ui-icon-refresh'>Recycle image</a>";
           function deleteImage($item, $fromTrash) {
               $item.fadeOut(function () {
                   var $list = $("ul", $fromTrash).length ?
                     $("ul", $fromTrash) :
                     $("<ul class='gallery ui-helper-reset'/>").appendTo($fromTrash);

                   $item.find("a.ui-icon-trash").remove();
                   $item.append(recycle_icon).appendTo($list).fadeIn(function () {
                       $item
                         .animate({ width: "65px" })
                       //.find("img")
                       //  .animate({ height: "35px" });
                   });
               });
           }

           // image recycle function
           var trash_icon = "<a href='link/to/trash/script/when/we/have/js/off' title='Delete this image' class='ui-icon ui-icon-trash'>Delete image</a>";
           function recycleImage($item, $fromGallery) {
               $item.fadeOut(function () {
                   $item
                     .find("a.ui-icon-refresh")
                       .remove()
                     .end()
                     //.css("width", "96px")
                     //.append(trash_icon)
                     //.find("img")
                     //  .css("height", "72px")
                     //.end()
                     .appendTo($fromGallery)
                     .fadeIn();
               });
           }
       });
   </script>
    <ul id="galleryTeam_@Model.idPosTeam" class="gallery ui-helper-reset ui-helper-clearfix">
        @foreach (var player in Model.ListPlayersTeam)
        {   
          <li id="@player.IdPlayer" salary="@player.Salary1" idTeam="@Model.idPosTeam" idGallery="galleryTeam_@Model.idPosTeam">
            <table style="width:40px; margin:0px;padding:0px">
                <tr style="height:10px;">
                    <td colspan="2">
                        <div class="playerName" style='white-space:nowrap;width:60px;height:15px;'>
                            <span>@player.Player.AbrevName</span>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td><img style="float:left" src="~/Images/Common/teams/Iconos/@player.LVNBAFranchis.Icono" width="15" height="15">
                        <a onclick="viewPlayerInfo(@player.IdPlayer)" title="More Info" class="ui-icon ui-icon-zoomin">More Info</a>
                    </td>
                    <td>    <img src="@player.Player.FaceImage" width="25" height="35"></td>
                </tr>
                <tr>
                    <td colspan="2">    @{var formated = String.Format("{0:#}", player.Salary1);var color = "red";
                   switch (player.IdCondition1)
                   {
                       case 0:
                           color="white";
                           break;
                       case 1:
                           color="red";
                           break;
                       case 2:
                           color = "#2E64FE";
                           break;
                       case 3:
                           color = "#01DF3A";
                           break;
                       case 4:
                           color = "violet";
                           break;
                       case 5:
                           color = "orange";
                           break;
                       default: color = "black"; break;
                   }
                   if (player.RookieRights == 1)
                       {
                           color = "green";
                       }
                    
                  
                @Html.TextBox("divSal2",player.Salary1, new{ id="salarioGallery"+player.IdPlayer, @class="salarioGallery", style = "float:left;width:55px; font-size:9px;background-color:" + color + ";color:white", maxlength = "14" });
                  var salCondition = player.Salary1;}
                </td>
                </tr>

            </table>

          </li>
        
        }
        </ul>

Liga.Web.Ux/Views/Trades/TransfersInfo.cshtml
@model IList<Liga.Domain.Entities.LVNBAFranchises>

    @{
        ViewBag.Title = "TransfersInfo";
        Layout = "~/Views/Shared/_WebWithoutColumnsLayout.cshtml";
    }
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12">
                <h2 class="h2">Transferibles en LVNBA</h2>
            </div>
            <div class="col-md-12 col-sm-12" id="cards">
                <div class="row">
                    @foreach (var LVNBAFranchises in Model)
                    {
                        <button style="background-color: Transparent; background-repeat:no-repeat; border: none; cursor:pointer; overflow: hidden; outline:none;" onclick="getTransferibles(@LVNBAFranchises.Id)">
                            <img height="75" width="75" class="rounded-circle" src="~/Images/Common/teams/Iconos/@LVNBAFranchises.Icono" />
                        </button>
                    }
                </div>
            </div>
            <div class="col-md-12 col-sm-12">
                <div class="row" id="detail">
                </div>
            </div>
        </div>
    </div>
    <br /><br /><br />

    <div class="modal fade" id="transferiblesModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="tituloModal">Jugadores transferibles</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="cuerpoModal">

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="noTransferiblesModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="tituloModal">No posee jugadores transferibles.</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <script>
        function getTransferibles(id) {
            $.ajax({
                type: "GET",
                cache: false,
                url: '@Url.Action("GetTransferibles", "Trades")',
                data: { idFranchise: id },
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (data) {
                    var liList = "";
                    var nombreEquipo = "";
                    var selectedTeam = false;
                    for (var i = 0; i < data.length; i++) {
                        if (!selectedTeam) {
                            nombreEquipo = data[i].Equipo;
                            selectedTeam = true;
                        }
                        liList = liList + '<li><img height="75" width="75" class="rounded-circle" src="' + window.location.origin +'/Images/Common/teams/Iconos/'+data[i].EquipoImagen.replace("jpg","png")+'" />' + data[i].Jugador + '</li>';
                    }
                    if (!selectedTeam) {
                        $('#noTransferiblesModal').modal('show');
                    }
                    else {
                        $("#tituloModal").text("Jugadores transferibles de '" + nombreEquipo + "':");
                        $("#cuerpoModal").empty();
                        $("#cuerpoModal").append("<ul>" + liList + "</ul>");
                        $('#transferiblesModal').modal('show');
                    }
                },
                error: function () {
                    alert('Por favor intente de nuevo.');
                }
            });
        }
    </script>