Liga.Web.Ux/Controllers/PlayersController.cs
using Liga.Domain.Entities;
using Liga.Infrastructure.Data;
using Liga.Infrastructure.Data.Repository;
using Omu.ValueInjecter;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using System.Web.Security;
using System.Web.UI.WebControls;

namespace Liga.Web.UI.Controllers
{
    
    public class PlayersController : BaseController
    {
        private Liga_DBContext db = new Liga_DBContext();
        private PlayerRepository playerRepository = new PlayerRepository();

        //
        // GET: /Players/

        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = string.IsNullOrEmpty(sortOrder) ? "Name_desc" : "";
            ViewBag.TeamSortParm = sortOrder == "Team" ? "Team_desc" : "Team";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            var players = db.Players.Include(p => p.LVNBAFranchis).Include(p => p.PlayersState).Include(p => p.PlayersPosition).Include(p => p.PlayersRole);
            if (!string.IsNullOrEmpty(searchString))
            {
                players = players.Where(s => s.CompleteName.ToUpper().Contains(searchString.ToUpper())
                                       || s.LVNBAFranchis.Name.ToUpper().Contains(searchString.ToUpper()));
            }
            switch (sortOrder)
            {
                case "Name_desc":
                    players = players.OrderByDescending(s => s.CompleteName);
                    break;
                case "Team":
                    players = players.OrderBy(s => s.LVNBAFranchis.Name);
                    break;
                case "Team_desc":
                    players = players.OrderByDescending(s => s.LVNBAFranchis.Name);
                    break;
                default:
                    players = players.OrderBy(s => s.CompleteName);
                    break;
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);

            return View(players.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult FreeAgent(string sortOrder, string currentFilter, string searchString, int? page, string message = "")
        {
            var par = db.Parameters.FirstOrDefault();
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = string.IsNullOrEmpty(sortOrder) ? "Name_desc" : "";
            ViewBag.Message = message;
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            var players = db.Players.Include(p => p.LVNBAFranchis).
                    Include(p => p.PlayersState).
                    Include(p => p.PlayersPosition).
                    Include(p => p.PlayersRole)
                    .Where(x => (x.ActualTeam == null || x.Cutted == 1 || x.PlayersSalariesFull.Where(pa => pa.DateSalarie.Year >= par.Temporada && pa.Salarie > 1).Count() == 0) && x.Retired == false );

            if (!string.IsNullOrEmpty(searchString))
            {
                players = players.Where(s => s.CompleteName.ToUpper().Contains(searchString.ToUpper()));
            }
            switch (sortOrder)
            {
                case "Name_desc":
                    players = players.OrderByDescending(s => s.CompleteName);
                    break;
                default:
                    players = players.OrderBy(s => s.CompleteName);
                    break;
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(players.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult RestrictedAgent(string sortOrder, string currentFilter, string searchString, int? page, string message = "")
        {
            int temporada = db.Parameters.First().Temporada;
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = string.IsNullOrEmpty(sortOrder) ? "Name_desc" : "";
            ViewBag.Message = message;
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            var players = db.Players
                    .Where(x => x.PlayersSalariesFull.Where(y => y.DateSalarie.Year >= temporada && (y.IdCondition == 1 || y.IdCondition == 3)).Count() > 0);
            if (!string.IsNullOrEmpty(searchString))
            {
                players = players.Where(s => s.CompleteName.ToUpper().Contains(searchString.ToUpper()));
            }
            switch (sortOrder)
            {
                case "Name_desc":
                    players = players.OrderByDescending(s => s.CompleteName);
                    break;
                default:
                    players = players.OrderBy(s => s.CompleteName);
                    break;
            }
            int pageSize = 30;
            int pageNumber = (page ?? 1);
            return View(players.ToPagedList(pageNumber, pageSize));
        }
        //
        // GET: /Players/Details/5

        public ActionResult Details(int id = 0)
        {
            Players players = db.Players.Find(id);
            if (players == null)
            {
                return HttpNotFound();
            }
            return View(players);
        }

        //
        // GET: /Players/Create
        [Authorize(Roles = "Administrador,Comisionado")]
        public ActionResult Create()
        {
            ViewBag.ActualTeam = new SelectList(db.LVNBAFranchises, "Id", "Name");
            ViewBag.IdState = new SelectList(db.PlayersStates, "Id", "State");
            ViewBag.IdPosition = new SelectList(db.PlayersPositions, "Id", "Position");
            ViewBag.IdRol = new SelectList(db.PlayersRoles, "Id", "Rol");
            ViewBag.Id = new SelectList(db.PlayersSalariesFull, "Id", "EuropeTeam");
            return View();
        }

        //
        // POST: /Players/Create
        [Authorize(Roles = "Administrador,Comisionado")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Players players)
        {

            if (ModelState.IsValid)
            {
                db.Players.Add(players);

                //creamos el salario del jugador por ahora vacio
                if(db.PlayersSalariesFull.Where(x=>x.IdPlayer == players.Id).FirstOrDefault() == null)
                {
                    DateTime fecha = DateTime.Now;
                    for (int i = 0; i < 5; i++)
                    {
                        var playerSalary = new PlayersSalariesFull
                        {
                            IdPlayer = players.Id,
                            IdLVNBAFranchises = players.ActualTeam.Value,
                            Salarie = 0,
                            DateSalarie = fecha,
                            IdCondition = 6
                        };
                        db.PlayersSalariesFull.Add(playerSalary);
                        fecha = new DateTime(fecha.Year+1, fecha.Month, fecha.Day);
                    }

                }
                PlayersHistories playerHistory = new PlayersHistories();
                if(db.PlayersHistories.Find(players.Id) == null && players.ActualTeam != null)
                {
                    playerHistory.IdPlayer = players.Id;
                    playerHistory.IdFranchise = players.ActualTeam.Value;
                    playerHistory.StartDate = DateTime.Now;
                    db.PlayersHistories.Add(playerHistory);
                }
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            ViewBag.ActualTeam = new SelectList(db.LVNBAFranchises.OrderBy(x => x.Name), "Id", "Name", players.ActualTeam);
            ViewBag.IdState = new SelectList(db.PlayersStates, "Id", "State", players.IdState);
            ViewBag.IdPosition = new SelectList(db.PlayersPositions, "Id", "Position", players.IdPosition);
            ViewBag.IdRol = new SelectList(db.PlayersRoles, "Id", "Rol", players.IdRol);
            ViewBag.Id = new SelectList(db.PlayersSalariesFull, "Id", "EuropeTeam", players.Id);
            return View(players);
        }

        //
        // GET: /Players/Tender/5
        
        public ActionResult Tender(int id = 0)
        {
            int franchise2 = 0;
            franchise2 = GetManagerTeam();
            if (franchise2 < 1)
                return RedirectToAction("Index");
            string salary = db.PlayersSalariesFull.Where(x => x.IdLVNBAFranchises == franchise2).Sum(x => x.Salarie).ToString();
            string LuxuryTax = db.Parameters.First().ImpuestoLujo.ToString();
            string SalaryTax = db.Parameters.First().LimiteSalarial.ToString();
            if (salary == null || salary == "") salary = "0";
            List<PlayersSalariesFull> playersSalariesFull = db.PlayersSalariesFull.Where(x => (x.IdLVNBAFranchises == franchise2 && x.IdPlayer == id && x.IdCondition == 4)).ToList();
            if (playersSalariesFull == null || playersSalariesFull.Count > 0)
            {
                return RedirectToAction("FreeAgent", new { message = "No puede volver a ofertar por este jugador." });
            }
            // Busca que la franquicia no tenga oferta activa de un jugador(oferta activa: Accepted y Rejected deben ser null, significa que aun esta sin resolucion desde el comisionado) 

Liga.Web.Ux/Views/Players/ChangePlayerTeam.cshtml
@model Liga.Domain.Entities.PlayersForChangeTeam

@{
    ViewBag.Title = "Estados";
    Layout = "~/Views/Shared/_ComissionLayout.cshtml";

}


<h2>Cambiar a un jugador de equipo implica: </h2>
<p>
    Sólo se pueden mover de equipo los jugadores no retirados o que no sean legalmente intransferibles.
    <br /> Si quieres cambiar de equipo a un jugador LI, debes primero cambiar su status desde administración.
    <br />Jugadores FA a los que se ficha deben abrir un nuevo salario. Luego las cantidades especificarlas desde administración
</p>
<div class="row mb-5 pb-5">
    <div class="col-md-4 mb-3">
        <div class="card">
            <div class="card-header">
                Cambiar el equipo que paga el salario.
            </div>
            <div class="card-body">
                El campo IdLVNBAFranchises pasa al nuevo equipo.
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                Eliminar su estado y su rol
            </div>
            <div class="card-body">
                El jugador en el nuevo equipo al empezar no tiene rol.
                Su estado  puede pasar a LEGALMENTE INTRANSFERIBLE y sino a NULO.
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                Cambio en histórico del jugador
            </div>
            <div class="card-body">
                El jugador cierra un ciclo con un equipo y abre otro ciclo con el nuevo.
            </div>
        </div>
    </div>
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div class="row">

        @Html.HiddenFor(model => model.Id)


        <div class="form-group col-md-4">
            @Html.Label("Equipo")
            @Html.TextBoxFor(model => model.CompleteName, new { disabled = "disabled", @class = "form-control disabled" })
        </div>

        <div class="form-group col-md-4">
            @Html.Label("Equipo Actual")
            @Html.TextBoxFor(model => model.FranchiseName, new { disabled = "disabled", @class="form-control disabled" })
        </div>
        <div class="form-group col-md-4">
            @Html.Label("Nuevo Equipo")
            @Html.DropDownList("ActualTeam", null, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ActualTeam)
        </div>
    </div>
    <div class="row justify-content-end mt-4">
        @Html.ActionLink("Volver", "PlayerActions", null, new { @class = "btn btn-dark col-md-1 mr-2" })
        <input type="submit" class="btn btn-outline-danger col-md-2" value="Guardar" />
    </div>
}



@section Scripts {
    @Scripts.Render("~/jqueryval")
}

Liga.Web.Ux/Views/Players/ConvertFA.cshtml
@model Liga.Domain.Entities.Players

@{
    ViewBag.Title = "Convertir FA";
    Layout = "~/Views/Shared/_ComissionLayout.cshtml";

}

<h2>Convertir a agente libre implica: </h2>
<div class="row mb-5 pb-5">
    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                Eliminar el salario que tiene el jugador.
            </div>
            <div class="card-body">
                Todos los años de contrato se borran.
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                Eliminar su estado y su rol
            </div>
            <div class="card-body">
                El jugador ya no tiene equipo y por lo tanto no tiene rol ni estado contractual
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                Dejar al jugador sin equipo
            </div>
            <div class="card-body">
                El jugador al convertirse en agente libre se queda sin equipo
            </div>
        </div>
    </div>
</div>

<fieldset>
    <legend class="mb-4 mt-5 font-weight-bold">Jugador</legend>
    <table class="table table-striped">
        <tr>
            <th>
                @Html.Label("Nombre")
            </th>
            <th>
                @Html.Label("Equipo")
            </th>
            <th>
                @Html.Label("Rol")
            </th>
            <th>
                @Html.Label("Posición")
            </th>
            <th>
                @Html.Label("Estado")
            </th>
            <th>
                @Html.Label("Derechos bird")
            </th>
        </tr>
        <tr>
            <td>
                @Html.DisplayFor(model => model.CompleteName)
            </td>
            <td>
                @Html.DisplayFor(model => model.LVNBAFranchis.Name)
            </td>
            <td>
                @Html.DisplayFor(model => model.PlayersRole.Rol)
            </td>
            <td>
                @Html.DisplayFor(model => model.PlayersPosition.Position)
            </td>
            <td>
                @Html.DisplayFor(model => model.PlayersState.State)
            </td>
            <td>
                @Html.DisplayFor(model => model.BirdRights)
            </td>
        </tr>
    </table>




</fieldset>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="row justify-content-end mt-4">
        @Html.ActionLink("Volver", "PlayerActions", null, new { @class = "btn btn-dark col-md-1 mr-2" })
        <input type="submit" class="btn btn-outline-danger col-md-2" value="Convertir a FA" />
    </div>
}

Liga.Web.Ux/Views/Players/Create.cshtml
@model Liga.Domain.Entities.Players

@{
    ViewBag.Title = "Jugadores";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<script type="text/javascript">

    $(document).ready(function () {
        jQuery.validator.methods.date = function (value, element) {
            var dateRegex = /^(0?[1-9]|[12]\d|3[01])\/(0?[1-9]|10|11|12)\/(19|20)\d\d(\D.*)?$/;
            return this.optional(element) || dateRegex.test(value);
        };

        $('#buttonID2').on({
            'click': function () {

                var imagePath = $("#mainImage").val();
                $('#mImage').attr('src', imagePath);
            }
        });
    })


</script>
<h2>Jugadores</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div class="row pb-5">
        <div class="form-group col-md-4">
            @Html.Label("Nombre")
            @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Name)
        </div>
        <div class="form-group col-md-4">
            @Html.Label("Apellido")
            @Html.TextBoxFor(model => model.FirstName, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.FirstName)
        </div>
        <div class="form-group col-md-4">
            @Html.Label("Apodo")
            @Html.TextBoxFor(model => model.NickName, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.NickName)
        </div>
        <div class="form-group col-md-4">
            @Html.Label("Altura")
            @Html.TextBoxFor(model => model.Height, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Height)
        </div>
        <div class="form-group col-md-4">
            @Html.Label("Peso")
            @Html.TextBoxFor(model => model.Weight, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Weight)
        </div>
        <div class="form-group col-md-4">
            @Html.Label("Equipo", "LVNBAFranchis")
            @Html.DropDownList("ActualTeam", null, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ActualTeam)
        </div>
        <div class="form-group col-md-4">
            @Html.Label("Rol")
            @Html.DropDownList("IdRol", null, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IdRol)
        </div>
        <div class="form-group col-md-4">
            @Html.Label("Posición")
            @Html.DropDownList("IdPosition", null, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IdPosition)
        </div>
        <div class="form-group col-md-4">
            @Html.Label("Fecha nacimiento")
            @Html.TextBoxFor(model => model.BornDate, new { @class = "form-control", type = "date" })
            @Html.ValidationMessageFor(model => model.BornDate)
        </div>
        <div class="form-group col-md-4">
            @Html.Label("Estado")
            @Html.DropDownList("IdState", null, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IdState)
        </div>
        <div class="form-group col-md-4">
            @Html.Label("Foto")
            @Html.TextBoxFor(model => model.FaceImage, new { id = "faceImage", @class = "form-control" })
            @Html.ValidationMessageFor(model => model.FaceImage)
        </div>
        <div class="form-group col-md-4">
            @Html.Label("Imagen")
            @Html.TextBoxFor(model => model.MainImage, new { id = "mainImage", @class = "form-control" })
            @Html.ValidationMessageFor(model => model.MainImage)
        </div>
        <img class="col-md-4" id="buttonID2" title="Visualizar" />
        <img class="col-md-4" id="mImage" width="150" height="200" src="" />
        <div class="form-group col-md-4">
            @Html.Label("Nivel 2k")
            @Html.TextBoxFor(model => model.Level2k, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Level2k)
        </div>
    </div>
    <div class="row pb-5 justify-content-end">
        <input class="btn btn-outline-success col-md-2 mr-1" type="submit" value="Crear" />
        @Html.ActionLink("Volver", "Index", null, new { @class = "btn btn-outline-dark col-md-2" })
    </div>
}

@section Scripts {
    @Scripts.Render("~/jqueryval")
}

Liga.Web.Ux/Views/Players/FreeAgent.cshtml
@model PagedList.IPagedList<Liga.Domain.Entities.Players>
    @using PagedList.Mvc;
    @{
        ViewBag.Title = "Jugadores Libres";
        Layout = "~/Views/Shared/_WebWithoutColumnsLayout.cshtml";
        string message = ViewBag.Message;
    }
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2>Jugadores Libres</h2>
            </div>
            @{
                if (message != null && message != "")
                {
                    <div class="col-md-12">
                        <ul><li style="color: red;">@message</li></ul>
                    </div>
                }
            }
            <div class="col-md-12">
                @using (Html.BeginForm("FreeAgent", "Players", FormMethod.Get))
                {
                    <p>
                        Buscar por nombre jugador: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
                        <input type="submit" value="Buscar" />
                    </p>
                }
            </div>
            <div class="col-md-12">
                <table class="table table-striped small">
                    <thead class="thead-dark">
                        <tr>

                            <th>
                                @Html.ActionLink("Nombre", "FreeAgent", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter }, new { @class = "order-table" })
                            </th>
                            <th>
                                @Html.DisplayName("Rol")
                            </th>
                            <th>
                                @Html.DisplayName("Posición")
                            </th>
                            <th>
                                @Html.DisplayName("Estado")
                            </th>
                            <th>
                                @Html.DisplayName("Nivel")
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CompleteName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.PlayersRole.Rol)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.PlayersPosition.Position)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.PlayersState.Abrev)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Level2k)
                                </td>
                                <td>
                                    @Html.ActionLink("Ofertar", "Tender", new { id = item.Id })
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <hr class="pag-sep">
            </div>
            <div class="col-md-3">
                <p class="pag-size">
                    Pagina @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) de @Model.PageCount
                </p>
            </div>
            <div class="col-md-9">
                @Html.PagedListPager(Model, page => Url.Action("FreeAgent", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
            </div>
        </div>
    </div>
    <br />
    <br />
    <br />

Liga.Web.Ux/Views/Players/Index.cshtml
@model PagedList.IPagedList<Liga.Domain.Entities.Players>
@using PagedList.Mvc; 
@{
    ViewBag.Title = "Jugadores";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";

}

<h2>Jugadores</h2>

<p>
    @Html.ActionLink("Crear Jugador", "Create")
</p>

@using (Html.BeginForm("Index", "Players", FormMethod.Get))
{
    <p>
        Buscar por nombre jugador o equipo: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)  
        <input type="submit" value="Buscar" />
    </p>
}
<table class="table table-striped small">
    <tr>
               
        <th>    
          @Html.ActionLink("Nombre", "Index", new { sortOrder=ViewBag.NameSortParm, currentFilter=ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Equipo", "Index", new { sortOrder = ViewBag.TeamSortParm, currentFilter=ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.DisplayName("Rol")
        </th>
        <th>
            @Html.DisplayName("Posición")
        </th>
        <th>
            @Html.DisplayName("Estado")
        </th>
        <th>
            @Html.DisplayName("Imagen")
        </th>
        <th>
            @Html.DisplayName("Nivel")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CompleteName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LVNBAFranchis.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PlayersRole.Rol)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PlayersPosition.Position)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PlayersState.Abrev)
        </td>
        <td>
            <img class="img-thumbnail"  width="40" height="60" src="@item.FaceImage" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Level2k)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Borrar", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>
<br />
<p style="color:red; font-weight:bold">
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
</p>
@Html.PagedListPager(Model , page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter=ViewBag.CurrentFilter }))

Liga.Web.Ux/Views/Players/PlayerActions.cshtml
@model PagedList.IPagedList<Liga.Domain.Entities.Players>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Acciones a jugador";
    Layout = "~/Views/Shared/_ComissionLayout.cshtml";

}

<h2>Acciones en jugadores</h2>
@using (Html.BeginForm("PlayerActions", "Players", FormMethod.Get))
{
<div class="row mb-5">
    <div class="col-md-6">
        Buscar por nombre jugador o equipo: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control" })
    </div>
    <div class="col-md-1">
        <button type="submit" class="btn btn-outline-info d-inline">Buscar</button>
    </div>
    <div class="col-md-1 mt-1">
        <a href="/Players/Create" class="btn btn-outline-dark d-inline">Crear Jugador</a>
    </div>
</div>
}
<table class="table table-striped small">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.ActionLink("Nombre", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("Equipo", "Index", new { sortOrder = ViewBag.TeamSortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th></th>
        </tr>
    </thead>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CompleteName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LVNBAFranchis.Name)
            </td>
            <td>
                @Html.ActionLink("Editar", "EditComission", new { id = item.Id })|
                @if (item.PlayersSalariesFull != null)
                {
                    <a href="/PlayersSalaries/Edit/@item.Id">Salario</a>
                }
                | @Html.ActionLink("Convertir FA", "ConvertFA", new { id = item.Id }) |
                @Html.ActionLink("Cortar", "CutPlayer", new { id = item.Id }) |
                @Html.ActionLink("Retirar", "RetirePlayer", new { id = item.Id }) |
                @Html.ActionLink("Cambiar equipo", "ChangePlayerTeam", new { id = item.Id }) |
                @Html.ActionLink("Fuera de NBA", "OutOfNBA", new { id = item.Id })

            </td>
        </tr>
    }

</table>

@Html.PagedListPager(Model, page => Url.Action("PLayerActions", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

<script type="text/javascript">
    $(document).ready(function () {
        $('.pagination').children().addClass('page-item');
        $('.page-item').children().addClass('page-link');
    })
</script>

Liga.Web.Ux/Views/Players/RestrictedAgent.cshtml
@model PagedList.IPagedList<Liga.Domain.Entities.Players>
    @using PagedList.Mvc;
    @{
        ViewBag.Title = "Agentes Restringidos";
        Layout = "~/Views/Shared/_WebWithoutColumnsLayout.cshtml";
    }
    <div class="row">
        <div class="col-md-12">
            @using (Html.BeginForm("RestrictedAgent", "Players", FormMethod.Get))
            {
                <br />
                <p>
                    Buscar por nombre jugador: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
                    <input type="submit" value="Buscar" />
                </p>
            }
        </div>
        <div class="col-md-12">
            <table class="table table-striped">
                <thead class="thead-dark">
                    <tr width="100%"><th><h5>Agentes Restringidos</h5></th></tr>
                </thead>
                <tbody>
                    <tr>
                        <td width="100%">
                            @foreach (var item in Model)
                            {
                                <div onclick="viewPlayerInfo(@item.Id)" style="cursor:pointer;float:left">

                                    @{Html.RenderPartial("PlayerCard", item);
                                    }
                                </div>
                            }
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <hr class="pag-sep">
        </div>
        <div class="col-md-3">
            <p class="pag-size">
                Pagina @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) de @Model.PageCount
            </p>
        </div>
        <div class="col-md-9">
            @Html.PagedListPager(Model, page => Url.Action("RestrictedAgent", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
        </div>
    </div>
    <br />
    <br />
    <br />