Liga.Web.Ux/Controllers/PlayersSalariesController.cs
using Liga.Domain.Entities;
using Liga.Infrastructure.Data;
using Liga.Infrastructure.Data.Repository;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Runtime.Serialization;
using System.Web.Mvc;

namespace Liga.Web.UI.Controllers
{
    [Authorize(Roles = "Administrador,Comisionado")]
    public class PlayersSalariesController : BaseController
    {
        private Liga_DBContext db = new Liga_DBContext();
        private DateTime Today = DateTime.Today;

        //
        // GET: /PlayersSalaries/

        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = string.IsNullOrEmpty(sortOrder) ? "Name_desc" : "";
            ViewBag.TeamSortParm = sortOrder == "Team" ? "Team_desc" : "Team";
            ViewBag.Today = db.Parameters.First().Temporada;
            ViewBag.Today1 = db.Parameters.First().Temporada+1;
            ViewBag.Today2 = db.Parameters.First().Temporada+2;
            ViewBag.Today3 = db.Parameters.First().Temporada+3;
            ViewBag.Today4 = db.Parameters.First().Temporada+4;
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            var players = db.Players.Include(p => p.PlayersSalariesFull).Where(p => !p.Retired);
            if (!string.IsNullOrEmpty(searchString))
            {
                players = players.Where(s => s.CompleteName.ToUpper().Contains(searchString.ToUpper())
                                       || s.LVNBAFranchis.Name.ToUpper().Contains(searchString.ToUpper()));
            }
            switch (sortOrder)
            {
                case "Name_desc":
                    players = players.OrderByDescending(s => s.CompleteName);
                    break;
                case "Team":
                    players = players.OrderBy(s => s.LVNBAFranchis.Name);
                    break;
                case "Team_desc":
                    players = players.OrderByDescending(s => s.LVNBAFranchis.Name);
                    break;
                default:
                    players = players.OrderBy(s => s.CompleteName);
                    break;
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);

            return View(players.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult IndexOld(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = string.IsNullOrEmpty(sortOrder) ? "Name_desc" : "";
            ViewBag.TeamSortParm = sortOrder == "Team" ? "Team_desc" : "Team";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            var playerssalaries = db.PlayersSalariesFull.Include(p => p.Player).Include(p => p.SalaryCondition);

            if (!string.IsNullOrEmpty(searchString))
            {
                playerssalaries = playerssalaries.Where(s => s.Player.CompleteName.ToUpper().Contains(searchString.ToUpper())
                                       || s.LVNBAFranchis.Name.ToUpper().Contains(searchString.ToUpper()));
            }
            switch (sortOrder)
            {
                case "Name_desc":
                    playerssalaries = playerssalaries.OrderByDescending(s => s.Player.CompleteName);
                    break;
                case "Team":
                    playerssalaries = playerssalaries.OrderBy(s => s.LVNBAFranchis.Name);
                    break;
                case "Team_desc":
                    playerssalaries = playerssalaries.OrderByDescending(s => s.LVNBAFranchis.Name);
                    break;
                default:
                    playerssalaries = playerssalaries.OrderBy(s => s.Player.CompleteName);
                    break;
            }
            int pageSize = 30;
            int pageNumber = (page ?? 1);

            return View(playerssalaries.ToPagedList(pageNumber, pageSize));
        }

        //
        // GET: /PlayersSalaries/Details/5

        public ActionResult Details(int id = 0)
        {
            var playerssalaries = db.PlayersSalariesFull.Find(id);
            if (playerssalaries == null)
            {
                return HttpNotFound();
            }
            return View(playerssalaries);
        }

        //
        // GET: /PlayersSalaries/Create

        public ActionResult Create()
        {
            ViewBag.IdLVNBAFranchises = new SelectList(db.LVNBAFranchises.OrderBy(x => x.Name), "Id", "Name");
            ViewBag.Id = new SelectList(db.Players.OrderBy(x=>x.CompleteName), "Id", "CompleteName");
            return View();
        }

        //
        // POST: /PlayersSalaries/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PlayersSalariesFull playerssalaries)
        {
            try
            {
                ViewBag.Id = new SelectList(db.Players.OrderBy(x => x.CompleteName), "Id", "CompleteName", playerssalaries.Id);
                ViewBag.IdLVNBAFranchises = new SelectList(db.LVNBAFranchises.OrderBy(x => x.Name), "Id", "Name",playerssalaries.IdLVNBAFranchises);

                if (ModelState.IsValid)
                {
                    string sMessage;

                    if (db.PlayersSalariesFull.Find(playerssalaries.Id) != null)
                    {
                        sMessage = "Este jugador ya tiene una ficha de salarios";
                        ModelState.AddModelError("", sMessage);
                        return View(playerssalaries); 
                    }
                    sMessage = ValidaCondicionSinSalario(playerssalaries);
                    if (sMessage != "")
                    {
                        ModelState.AddModelError("", sMessage);
                        return View(playerssalaries);
                    }
                    db.PlayersSalariesFull.Add(playerssalaries);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException ex)
            {

                ModelState.AddModelError("", "No se ha podido guardar: " + ex.InnerException.ToString());
            }


                return View(playerssalaries);
        }

        //
        // GET: /PlayersSalaries/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Players player = db.Players.Find(id);
            if (player == null)
            {
                return HttpNotFound();
            }
            PlayerSalariesModel playerSalariesModel = new PlayerSalariesModel();
            int condition1, condition2, condition3, condition4, condition5 = 0;
            decimal salarie1, salarie2, salarie3, salarie4, salarie5;
            Today = new DateTime(db.Parameters.First().Temporada, 01, 01);
            PlayersSalariesFull playersSalariesFull1 = player.PlayersSalariesFull.ToList().Find(x => (x.IdPlayer == player.Id) && (x.DateSalarie.Year == Today.Year));
            PlayersSalariesFull playersSalariesFull2 = player.PlayersSalariesFull.ToList().Find(x => (x.IdPlayer == player.Id) && (x.DateSalarie.Year == Today.AddYears(1).Year));
            PlayersSalariesFull playersSalariesFull3 = player.PlayersSalariesFull.ToList().Find(x => (x.IdPlayer == player.Id) && (x.DateSalarie.Year == Today.AddYears(2).Year));
            PlayersSalariesFull playersSalariesFull4 = player.PlayersSalariesFull.ToList().Find(x => (x.IdPlayer == player.Id) && (x.DateSalarie.Year == Today.AddYears(3).Year));
            PlayersSalariesFull playersSalariesFull5 = player.PlayersSalariesFull.ToList().Find(x => (x.IdPlayer == player.Id) && (x.DateSalarie.Year == Today.AddYears(4).Year));

            if (playersSalariesFull1 != null)
            {
                condition1 = playersSalariesFull1.IdCondition;
                salarie1 = playersSalariesFull1.Salarie;
            }
            else
            {
                condition1 = 6;
                salarie1 = 0;
            }
            if (playersSalariesFull2 != null)
            {
                condition2 = playersSalariesFull2.IdCondition;
                salarie2 = playersSalariesFull2.Salarie;
            }
            else
            {
                condition2 = 6;
                salarie2 = 0;
            }
            if (playersSalariesFull3 != null)
            {
                condition3 = playersSalariesFull3.IdCondition;
                salarie3 = playersSalariesFull3.Salarie;
            }
            else
            {
                condition3 = 6;
                salarie3 = 0;
            }
            if (playersSalariesFull4 != null)
            {
                condition4 = playersSalariesFull4.IdCondition;
                salarie4 = playersSalariesFull4.Salarie;
            }
            else
            {
                condition4 = 6;
                salarie4 = 0;
            }
            if (playersSalariesFull5 != null)
            {
                condition5 = playersSalariesFull5.IdCondition;
                salarie5 = playersSalariesFull5.Salarie;
            }
            else
            {
                condition5 = 6;
                salarie5 = 0;
            }

            playerSalariesModel.IdCondition1 = condition1;
            playerSalariesModel.IdCondition2 = condition2;
            playerSalariesModel.IdCondition3 = condition3;
            playerSalariesModel.IdCondition4 = condition4;
            playerSalariesModel.IdCondition5 = condition5;

Liga.Web.Ux/Views/PlayersSalaries/Create.cshtml
@model Liga.Domain.Entities.PlayersSalaries

@{
    ViewBag.Title = "Salarios";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";

}
<script type="text/javascript">
    $(document).ready(function () {
        $('#Id').change(function () {
            var selectedPlayer = $(this).val();
            if (selectedPlayer != null && selectedPlayer != '') {
                $.getJSON('@Url.Action("GetTeamByPlayer")', { idPlayer: selectedPlayer }, function (idTeam) {
                    $("#IdLVNBAFranchises").val(idTeam);
                });
            }
        });
    });
</script>
<h2>Salarios</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div class="row">
        @Html.HiddenFor(model => model.Id)

        <div class="form-group col-md-4">
            @Html.Label("Equipo")
            @Html.DropDownList("IdLVNBAFranchises", null, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IdLVNBAFranchises)
        </div>

        <div class="form-group col-md-4">
            @Html.Label("Salario 1")
            @{var formated = String.Format("{0:#}", Model.Salary1);}
            @Html.TextBoxFor(model => model.Salary1, formated, new { id = "divSal1", @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Salary1)
        </div>

        <div class="form-group col-md-4">
            @Html.Label("Condición 1")
            @Html.DropDownList("IdCondition1", null, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IdCondition1)
        </div>
        <div class="form-group col-md-4">
            @Html.Label("Salario 2")
            @{formated = String.Format("{0:#}", Model.Salary2);}
            @Html.TextBoxFor(model => model.Salary2, formated, new { id = "divSal2", @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Salary2)
        </div>
        <div class="form-group col-md-4">
            @Html.Label("Condición 2")
            @Html.DropDownList("IdCondition2", null, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IdCondition2)
        </div>
        <div class="form-group col-md-4">
            @Html.Label("Salario 3")
            @{formated = String.Format("{0:#}", Model.Salary3);}
            @Html.TextBoxFor(model => model.Salary3, formated, new { id = "divSal3", @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Salary3)
        </div>
        <div class="form-group col-md-4">
            @Html.Label("Condición 3")
            @Html.DropDownList("IdCondition3", null, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IdCondition3)
        </div>
        <div class="form-group col-md-4">
            @Html.Label("Salario 4")
            @{formated = String.Format("{0:#}", Model.Salary4);}
            @Html.TextBoxFor(model => model.Salary4, formated, new { id = "divSal4", @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Salary4)
        </div>
        <div class="form-group col-md-4">
            @Html.Label("Condición 4")
            @Html.DropDownList("IdCondition4", null, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IdCondition4)
        </div>
        <div class="form-group col-md-4">
            @Html.Label("Salario 5")
            @{formated = String.Format("{0:#}", Model.Salary5);}
            @Html.TextBoxFor(model => model.Salary5, formated, new { id = "divSal5", @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Salary5)
        </div>
        <div class="form-group col-md-4">
            @Html.Label("Condición 5")
            @Html.DropDownList("IdCondition5", null, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IdCondition5)
        </div>
        <div class="form-group col-md-4">
            @Html.Label("Salario 6")
            @{formated = String.Format("{0:#}", Model.Salary6);}
            @Html.TextBoxFor(model => model.Salary6, formated, new { id = "divSal6", @class = "form-control" })

            @Html.ValidationMessageFor(model => model.Salary6)
        </div>
        <div class="form-group col-md-4">
            @Html.Label("Condición 6")
            @Html.DropDownList("IdCondition6", null, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IdCondition6)
        </div>
        <div class="form-group col-md-4">
            @Html.LabelFor(model => model.EuropeTeam)
            @Html.TextBoxFor(model => model.EuropeTeam, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.EuropeTeam)
        </div>
    </div>
    <div class="row pb-5 justify-content-end">
        <input class="btn btn-outline-success col-md-2 mr-1" type="submit" value="Crear" />
        @Html.ActionLink("Volver", "Index", null, new { @class = "btn btn-outline-dark col-md-2" })
    </div>
}


@section Scripts {
    @Scripts.Render("~/jqueryval")
}

Liga.Web.Ux/Views/PlayersSalaries/Delete.cshtml
@model Liga.Domain.Entities.Players

@{
    ViewBag.Title = "Salarios";
    Layout = "~/Views/Shared/_WebOneColumnForStats.cshtml";
}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2>Borrar salario de @Html.DisplayFor(model => model.CompleteName) </h2>
        </div>
        <div class="col-md-12">

            <h3>Está seguro?</h3>
            <fieldset>
                <legend>Salarios</legend>
                <table class="table table-striped small">
                    <thead class="thead-dark">
                        <tr>
                            <th>Año</th>
                            <th>Salario</th>
                            <th>Condicion</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{ foreach (var salario in Model.PlayersSalariesFull)
                            {
                                <tr>
                                    <td>@salario.DateSalarie.Year</td>
                                    <td>@salario.Salarie</td>
                                    <td>@salario.SalaryCondition.Condition</td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>

            </fieldset>
            @using (Html.BeginForm("DeleteConfirmed", "PlayersSalaries", new { id = Model.Id }))
            {
                @Html.AntiForgeryToken()
                <p>
                    <input class="btn btn-outline-danger col-md-2 mr-1" type="submit" value="Borrar" /> |
                    @Html.ActionLink("Volver", "Index", null, new { @class = "btn btn-outline-dark col-md-2" })
                </p>
            }
            <br />
            <br />
        </div>
    </div>
</div>

Liga.Web.Ux/Views/PlayersSalaries/DeleteOld.cshtml
@model Liga.Domain.Entities.PlayersSalaries

@{
    ViewBag.Title = "Salarios";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Borrar salario de   @Html.DisplayFor(model => model.Player.CompleteName) </h2>

<h3>Está seguro?</h3>
<fieldset>
    <legend>Salarios</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Salary1)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Salary1)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Salary2)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Salary2)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Salary3)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Salary3)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Salary4)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Salary4)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Salary5)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Salary5)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Salary6)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Salary6)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.SalaryCondition.Condition)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SalaryCondition.Condition)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.SalaryCondition1.Condition)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SalaryCondition1.Condition)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.SalaryCondition2.Condition)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SalaryCondition2.Condition)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.SalaryCondition3.Condition)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SalaryCondition3.Condition)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.SalaryCondition4.Condition)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SalaryCondition4.Condition)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.SalaryCondition5.Condition)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SalaryCondition5.Condition)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.EuropeTeam)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.EuropeTeam)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LVNBAFranchis.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LVNBAFranchis.Name)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Borrar" /> |
        @Html.ActionLink("Volver", "Index")
    </p>
}

Liga.Web.Ux/Views/PlayersSalaries/Edit.cshtml
@model Liga.Domain.Entities.PlayerSalariesModel

@{
    ViewBag.Title = "Salarios";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    var Today = DateTime.Today;

}
<script type="text/javascript">
    $(document).ready(function () {
        $('#divSal1').autoNumeric('init', { aSep: ',', aDec: '', mDec: '0' });
        $('#divSal2').autoNumeric('init', { aSep: ',', aDec: '.', mDec: '0' });
        $('#divSal3').autoNumeric('init', { aSep: ',', aDec: '.', mDec: '0' });
        $('#divSal4').autoNumeric('init', { aSep: ',', aDec: '.', mDec: '0' });
        $('#divSal5').autoNumeric('init', { aSep: ',', aDec: '.', mDec: '0' });
    });
</script>
<h2>Editar salario de   @Html.DisplayFor(model => model.CompleteName) </h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div class="row">
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.CompleteName)

        <div class="form-group col-md-12">
            @Html.Label("Equipo")
            @Html.DropDownList("ActualTeam", null, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ActualTeam)
        </div>

        <div class="form-group col-md-6">
            @Html.Label("Salario" + Model.Today)
            @{var formated = String.Format("{0:#}", Model.Salarie1);}
            @Html.TextBoxFor(model => model.Salarie1, formated, new { id = "divSal1", @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Salarie1)
        </div>

        <div class="form-group col-md-6">
            @Html.Label("Condición")
            @Html.DropDownList("IdCondition1", null, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IdCondition1)
        </div>

        <div class="form-group col-md-6">
            @Html.Label("Salario" + (Model.Today + 1))
            @{formated = String.Format("{0:#}", Model.Salarie2);}
            @Html.TextBoxFor(model => model.Salarie2, formated, new { id = "divSal2", @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Salarie2)
        </div>

        <div class="form-group col-md-6">
            @Html.Label("Condición")
            @Html.DropDownList("IdCondition2", null, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IdCondition2)
        </div>

        <div class="form-group col-md-6">
            @Html.Label("Salario" + (Model.Today + 2))
            @{formated = String.Format("{0:#}", Model.Salarie3);}
            @Html.TextBoxFor(model => model.Salarie3, formated, new { id = "divSal3", @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Salarie3)
        </div>

        <div class="form-group col-md-6">
            @Html.Label("Condición")
            @Html.DropDownList("IdCondition3", null, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IdCondition3)
        </div>

        <div class="form-group col-md-6">
            @Html.Label("Salario" + (Model.Today + 3))
            @{formated = String.Format("{0:#}", Model.Salarie4);}
            @Html.TextBoxFor(model => model.Salarie4, formated, new { id = "divSal4", @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Salarie4)
        </div>

        <div class="form-group col-md-6">
            @Html.Label("Condición")
            @Html.DropDownList("IdCondition4", null, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IdCondition4)
        </div>

        <div class="form-group col-md-6">
            @Html.Label("Salario" + (Model.Today + 4))
            @{formated = String.Format("{0:#}", Model.Salarie5);}
            @Html.TextBoxFor(model => model.Salarie5, formated, new { id = "divSal5", @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Salarie5)
        </div>

        <div class="form-group col-md-6">
            @Html.Label("Condición")
            @Html.DropDownList("IdCondition5", null, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IdCondition5)
        </div>
    </div>
    <div class="row pb-5 justify-content-end">
        <input class="btn btn-outline-success col-md-2 mr-1" type="submit" value="Editar" />
        @Html.ActionLink("Volver", "Index", null, new { @class = "btn btn-outline-dark col-md-2" })
    </div>
}

@section Scripts {
    @Scripts.Render("~/jqueryval")
}

Liga.Web.Ux/Views/PlayersSalaries/IndexOld.cshtml
@model PagedList.IPagedList<Liga.Domain.Entities.PlayersSalaries>
@using PagedList.Mvc; 
@{
    ViewBag.Title = "Salarios";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";

}

    <script type="text/javascript">
        $(document).ready(function () {
            $('#salary1').autoNumeric('init', { aSep: '.', aDec: ',', mDec: '' });

        });
    </script>
<h2>Salarios Jugadores</h2>

<p>
    @Html.ActionLink("Crear nuevo", "Create")
</p>
@using (Html.BeginForm("Index", "PlayersSalaries", FormMethod.Get))
{
    <p>
        Buscar por nombre jugador o equipo: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)  
        <input type="submit" value="Buscar" />
    </p>
}
<table style="float:right;width:750px">
    <tr>
        <th>
          @Html.ActionLink("Nombre", "Index", new { sortOrder=ViewBag.NameSortParm, currentFilter=ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Equipo", "Index", new { sortOrder = ViewBag.TeamSortParm, currentFilter=ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.DisplayName("Salario 1")
        </th>
        <th>
            @Html.DisplayName("C")
        </th>
        <th>
            @Html.DisplayName("Salario 2")
        </th>
        <th>
            @Html.DisplayName("C")
        </th>

        <th>
            @Html.DisplayName("Salario 3")
        </th>
        
        <th>
            @Html.DisplayName("C")
        </th>
        <th>
            @Html.DisplayName("Salario 4")
        </th>
        <th>
            @Html.DisplayName("C")
        </th>
        <th>
            @Html.DisplayName("Salario 5")
        </th> 
        <th>
            @Html.DisplayName("C")
        </th>
        <th>
            @Html.DisplayName("Salario 6")
        </th>
        <th>
            @Html.DisplayName("C")
        </th>
        <th>
            @Html.DisplayName("Equipo europeo")
        </th>
        <th></th>
    </tr>
    <tr><td colspan="15"><hr /></td></tr>
@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Player.CompleteName)
        </td>
         <td >
            @Html.DisplayFor(modelItem => item.LVNBAFranchis.Abbreviation)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Salary1,"MyDecimalTemplate")
        </td>
        <td style="color:red">
            @Html.DisplayFor(modelItem => item.SalaryCondition.Abrev)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Salary2,"MyDecimalTemplate")
        </td>
        <td style="color:red">
            @Html.DisplayFor(modelItem => item.SalaryCondition1.Abrev)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Salary3,"MyDecimalTemplate")
        </td> 
        <td style="color:red">
            @Html.DisplayFor(modelItem => item.SalaryCondition2.Abrev)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Salary4,"MyDecimalTemplate")
        </td>
        <td style="color:red">
            @Html.DisplayFor(modelItem => item.SalaryCondition3.Abrev)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Salary5,"MyDecimalTemplate")
        </td>
        <td style="color:red">
            @Html.DisplayFor(modelItem => item.SalaryCondition4.Abrev)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Salary6,"MyDecimalTemplate")
        </td>
        <td style="color:red">
            @Html.DisplayFor(modelItem => item.SalaryCondition5.Abrev)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EuropeTeam)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.Id }) 
            @Html.ActionLink("Borrar", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>
<p style="color:red; font-weight:bold">
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
</p>
@Html.PagedListPager(Model , page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter=ViewBag.CurrentFilter }))